# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 260f273fa01897371fbae8209ccdd3c46156e985c01cb318602637d413c2988a9879a83e2987309b3f259813ee0a5834291fcbc942ed584031adcd275a00d915

test:
  secret_key_base: 91953411ecf0331038905815e217647d2b5e69a6778f2848babcffe23555d156b049e181206a1679703b4bb2698fc5f97f616963b6d6b3bdc2cc98bac0500863

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
